version: "3.8"
services:
  app:
    build:
      args:
        user: sapar
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: spanndback
    container_name: spanndback-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - spanndback

  # db:
  #   image: mysql:8.0.31
  #   container_name: spanndback-db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   networks:
  #     - spanndback

  db:
    image: postgres:latest
    container_name: spanndback-db-postgres
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      # PGDATA: /var/lib/postgresql/data
    networks:
      - spanndback

  adminer:
    image: adminer
    container_name: spanndback-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - spanndback

  nginx:
    image: nginx:1.17-alpine
    container_name: spanndback-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - spanndback

  redis:
    image: redis:latest
    container_name: spanndback-redis
    # command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ./redis:/data #maybe for cache driver in .env
    ports:
      - "6379:6379"
    networks:
      - spanndback

networks:
  spanndback:
    driver: bridge
