version: "3.8"
services:
  app:
    build:
      args:
        user: sapar
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: rabbitone
    container_name: rabbitone-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rabbitone

  # db:
  #   image: mysql:8.0.31
  #   container_name: rabbitone-db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   networks:
  #     - rabbitone

  db:
    image: postgres:latest
    container_name: rabbitone-db-postgres
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      # PGDATA: /var/lib/postgresql/data
    networks:
      - rabbitone

  adminer:
    image: adminer
    container_name: rabbitone-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - rabbitone

  nginx:
    image: nginx:1.17-alpine
    container_name: rabbitone-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - rabbitone

  redis:
    image: redis:latest
    container_name: rabbitone-redis
    # command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ./redis:/data #maybe for cache driver in .env
    ports:
      - "6379:6379"
    networks:
      - rabbitone

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitone-rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitone

networks:
  rabbitone:
    driver: bridge
